
DELETE http://localhost:3030/columns/67056ed1ed54f3caf7145040
Accept: application/json

###
GET http://localhost:3030/columns/67056dc1ed54f3caf714503d
Accept: application/json

###
###
PATCH http://localhost:3030/columns/670580b53dad6a183078f87f
Content-Type: application/json

{
  "tasks_array": [
    {
      "id": "1",
      "content": "some text",
      "order": 1,
      "done": false
    },
    {
      "id": "2",
      "content": "some text 2",
      "order": 2,
      "done": false
    },
    {
      "id": "3",
      "content": "some text 3",
      "order": 3,
      "done": false
    }
  ]
}

###
POST http://localhost:3030/columns
Content-Type: application/json

{
  "name": "columnsList Array",
  "board_id": "670579e4269cbcaca816d630"
}

###
### GET request to example server
GET http://localhost:3030/columns

###
